### ISSUE TITLE
Does not work on multiplayer server 50% of the time.

### ISSUE THREAD

**Issue by randomdude634** [JSJBDEV/ValkyrienRelogs#1]
When using in multiplayer server it does not work a good 50% of the time, no rhyme or reason to errors if this is user error please educate on what is wrong.

**Comment by JSJBDEV** [comment]
Are you using the forge or the fabric version?

**Comment by randomdude634** [comment]
Fabric

**Comment by JSJBDEV** [comment]
The only thing I can say is that it should work as long as the reason why the ship moved on a server is because another player was piloting it. Was this the case for you?

**Comment by JSJBDEV** [comment]
This should be fixed as of 0.3.0 https://modrinth.com/mod/valkyrien-relogs/versions
