### ISSUE TITLE
Where are you, dev, the mod isn't working 😭

### ISSUE THREAD

**Issue by TsameCorvy** [JSJBDEV/ValkyrienRelogs#4]
While I was playtesting my modpack in a 1.20.1 Forge Server made for Multiplayer, I decided to test how well Eureka Ships worked and also how this mod worked.

First off, while the recipe has been added, it is nowhere to be seen on the Creative Menu or JEI at all unless I see uses for Amethyst Shards or Blackstone Pressure Plates.

Secondly, it works until the part it has to relog me on a moving ship. Right Clicking the Anchor made me an officer, okay, I enabled cruise control, logged off, waited a bit, then logged in again, and it appears I fell off the ship. 💀💀💀💀💀💀💀

**Comment by JSJBDEV** [comment]
The recipe doesn't show up because it isn't in any creative tab. 
VS ships don't exist If there is no player nearby they are not entities, so most likely you fell off because it didn't exist for a while. I cannot confirm that here though, you would have to try with another player on the ship

**Comment by TsameCorvy** [comment]
Right, I tried it rn with another player but I couldn't interact with the Anchor after I was already registered as an officer even if said player was in a "3ish block radius" to the ship.

**Comment by JSJBDEV** [comment]
So it looks like there might be something that is in general breaking the mod in forge - whenever I try and log out then log back in to a singleplayer world it freezes but I can't work out why, this may be why teleporting isn't working, as it is struggling to put the player back in the world.

**Comment by JSJBDEV** [comment]
This is fixed on https://modrinth.com/mod/valkyrien-relogs/version/KkIoDS4h
